name: deploy to brainfeaster

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Copy
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.API_GITHUB_TOKEN }}
          src_path: ./
          src_branch: proBuid
          dst_path: /techpass
          dst_owner: brainfeaster
          dst_repo_name: brainfeaster.github.io
          username: sanjaipk
